---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sr-sa
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
subjects:
  - kind: ServiceAccount
    name: sr-sa
roleRef:
  kind: Role
  name: secret-reader

